---
title: "Titre du project"
subtitle: "Projet de recherche - Groupe ..."
author: "Nom Prénom, Nom Prénom et ..."
---

# Introduction (3 à 5 paragraphes)

Paragraphes d'introduction dans lesquelles vous présentez un aperçu de votre projet.

- Ancrage théorique et travaux existants sur le sujet.
    - Vous n'avez pas le temps d'effectuer une revue exhaustive de la littérature.
    - Présentez quelques articles sur votre sujet pour constituer une base théorique.
    - Utilisez ces articles pour faire valoir votre étude ou montrer pourquoi votre étude est importante
- Quelle est votre question de recherche/problématique?
    - Pourquoi est-ce important de s'intéresser à celle-ci?
- Quelles sont vos hypothèses?
    - À quoi est-ce que vous vous attendez sachant ce que la théorie nous dit actuellement?

# Données et méthode (3 à 5 paragraphes)

Présentez vos données et votre démarche méthodologique. Similaire à une recette de cuisine: vous avez besoin d'ingrédients et d'étapes de préparation.

## Population et échantillon d'étude

- Comment allez-vous sélectionner les cas/observations pour votre étude? Pourquoi?
    - Quels sont les critères pour sélectionner les cas qui constitueront votre échantillon?
- Quelle sera la taille de l'échantillon pour votre étude? Pourquoi?

## Méthodologie de la recherche

- Quel type d'étude allez-vous effectuer? (une étude de cas, une exploration d'un thème, ...)?
- Pourquoi est-ce que la méthode proposé est pertinente pour répondre à votre question?
- Quelles seront vos sources de données?
- Comment allez-vous collecter les données? Sur quelle période?
- Comment allez-vous analyser/coder les données?

## Biais, éthique et gestion des données

- Comment allez-vous gérer les biais et contrôler la qualité de l'étude?
    - Quels biais prévoyez-vous?
    - Comment allez-vous gérer ce(s) biais?
- Où vous vous situez en tant que chercheur par rapport au sujet étudié?
- Comment allez-vous gérer et stocker les données que vous collectez (sécuriser les données)?

## Discussion (1 à 2 paragraphes)

Présentez vos attentes en termes de résultats (aides vous de vos hypothèses).

- Quelles sont les inconnues et risques à ce stades?
- Quelles sont les limites de votre projet de recherche?
- Comment pourrait l'améliorer davantage?
- Que pourrait-on changer ou faire différemment?

## Bibliographie
- Vous devez lister TOUTES les sources auxquelles vous faites référence directement ou indirectement dans votre projet.
- Que ce soit pour les citations et la bibliogrpahie vous devez utiliser le format
    - APA: https://www.mendeley.com/guides/apa-citation-guide

